name: Continuous Integration with GitHub Action

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build JAR with Maven
      run: mvn clean package

    - name: Dockerfile build
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/upload-download-api-img:latest

    - name: Push to Docker Hub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/upload-download-api-img:latest ${{ secrets.DOCKER_USERNAME }}/upload-download-api-img:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/upload-download-api-img:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/upload-download-api-img:latest
